# Turn the components of the linter individualy on / off.
clangformat: off
cpplint: on
yapf: on
pylint: on

# If this whitelist block is present, the linter only operates on the files and
# directories listed in this whitelist.
whitelist:
 - msckf/include
 - msckf/okvis
 - msckf/src
 - msckf/test
