# Turn the components of the linter individualy on / off.
clangformat: on
cpplint: on
yapf: on
pylint: on

# If this whitelist block is present, the linter only operates on the files and
# directories listed in this whitelist.
whitelist:
 - msckf2/include
 - msckf2/okvis
 - msckf2/src
 - msckf2/test
