%YAML:1.0
# LoopClosureDetector parameters:
loop_closure_method: 1
use_nss: 1
alpha: 0.001
min_temporal_matches: 1
dist_local: 10
max_db_results: 50
min_nss_factor: 0.05
min_matches_per_group: 1
max_intragroup_gap: 3
max_distance_between_groups: 3
max_distance_between_queries: 2

lowe_ratio: 0.7
matcher_type: 4
min_correspondences: 12
max_ransac_iterations_stereo: 50
ransac_threshold_stereo: 9
ransac_inlier_threshold_stereo: 0.3
relative_pose_opt_iterations: 15
relative_pose_info_damper: 0.9

nfeatures: 500
scale_factor: 1.2
nlevels: 8
edge_threshold: 31
first_level: 0
WTA_K: 2
score_type_id: 0
patch_sze: 31
fast_threshold: 20

pgo_uniform_weight: false
pgo_rot_threshold: 0.5
pgo_trans_threshold: 10

# matcher_type options:
#   1: FLANNBASED
#   2: BRUTEFORCE
#   3: BRUTEFORCE_L1
#   4: BRUTEFORCE_HAMMING
#   5: BRUTEFORCE_HAMMINGLUT
#   6: BRUTEFORCE_SL2
